name: pkg-pr-new

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - run: bun i -g @antfu/ni

      - name: Install dependencies
        run: ni

      - name: Build
        run: nr build

      - run: nlx pkg-pr-new publish
